sonar.projectKey=org.sonarqube:java-sonar-runner-simple
sonar.projectName=Test 2026 03 17
sonar.projectVersion=1.0

sonar.sources=src

sonar.language=java

sonar.sourceEncoding=UTF-8
sonar.scm.disabled=true
sonar.host.url=http://localhost:9000
sonar.login=sqa_96392fd4d378075f2fcad43e70fc13f88cf167a4