sonar.projectKey=proyecto
sonar.projectName=proyecto
sonar.projectVersion=1.0

sonar.sources=src

sonar.sourceEncoding=UTF-8
sonar.scm.disabled=true
sonar.host.url=http://localhost:9000
sonar.token=sqp_d71def2e17aa0513e59b3781aa02f55c0f82911b